# Lab notebook - week 2

### * A note about cell output - expressions vs. statements

In [1]:
# Some code fragments produce output, see the red "Out[?]" below - such fragments are called expressions.
5 + 2

7

In [2]:
# Other fragments produce no output. Such fragments are called statements. Not that there is no "Out[]" below this cell.
x = 5 + 2

In [3]:
# If you want to see the value of x, just write x on another line, "x" is an "expression" and produces the value of x as output
y = 3 + 7
y

10

In [4]:
# A cell only produces one output - that of the last expression in the cell
x  # value of x is not shown
y 

10

In [5]:
# If you want to see several values, output them from different cells or use print()
# note that print() produces text, but it is not labeled as Out[] (why?)
print(x)
print(y)

7
10


## NumPy basics
Python lists are somewhat weird creatures. In contrast to basic array types in other languages like C# and Java, they can hold objects of different types and new elements can be inserted in the middle. NumPy arrays are much more like C# arrays - all elements have the same type.

In [6]:
# by convention numpy is always imported as np
import numpy as np

### Common ways of creating numpy arrays

In [7]:
a = np.array([5, 2, 17])  # Convert a Python list into a numpy array
a

array([ 5,  2, 17])

In [8]:
# List of lists gets converted into a 2D array
np.array([[5, 7, 2],
          [9, 4, 1]])


array([[5, 7, 2],
       [9, 4, 1]])

In [9]:
np.arange(5)  # Same as Python's range() but creates a numpy array
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [10]:
np.zeros(5)  # Create a numpy array with five elements, all set to zero

array([0., 0., 0., 0., 0.])

In [11]:
c = np.ones(7)  # Create a numpy array with five elements, all set to 1
c


array([1., 1., 1., 1., 1., 1., 1.])

In [12]:
# Array of 6 random numbers between 0 and 1
np.random.rand(6)

array([0.95680458, 0.21808278, 0.83799943, 0.16420849, 0.50725013,
       0.81290274])

In [13]:
# array with 6 random integers between 0 and 100 (not including 100 as usual)
np.random.randint(100, size=6)

array([88, 99, 35, 93, 22, 36])

### Array properties

In [14]:
a = np.array([[5, 7, 2],
              [9, 4, 1]])
b

NameError: name 'b' is not defined

In [15]:
# The total number of elements
a.size 

6

In [16]:
# number of dimensions
a.ndim 

2

In [17]:
# array shape is a Python tuple, in this case it's (2, 3) because b is a 2 by 3 array.
b.shape

NameError: name 'b' is not defined

In [18]:
# Data type of the array
a.dtype

dtype('int64')

In [19]:
# Note that zeros byt default uses the float64 data type
z = np.zeros(7)
z.dtype

dtype('float64')

In [20]:
# But data type can be set explicitly, almost all numpy functions that create arrays take an optional dtype parameter
# Let's set it to an 8 bit integer
z = np.zeros(7, dtype=np.int8)  
z.dtype

dtype('int8')

## Exercises

Read section 2.2 of the book (The Basics of NumPy Arrays) and complete the tasks below.


#### Convert a list into a numpy array

In [21]:
lst = [5, 3, 8, 4]
np.array(lst)

array([5, 3, 8, 4])

In [22]:
# your code here
x = [23, 43, 54, 234]
np.array(x)

array([ 23,  43,  54, 234])

#### What happens when you multiply a list by 3, what a about an array multiplied by 3?

In [23]:
# Feel free to add more cells
lst = [1, 2, 3, 4, 5]
print(lst * 3)
np.array(lst) * 3

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


array([ 3,  6,  9, 12, 15])

#### Create an array of 10 ones

In [24]:
np.ones(10, dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

#### Create an array of 10 fives

In [25]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50 (including 50)

In [26]:
np.arange(10, 51)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of 10 random numbers between 0 and 5 (not integers)

In [27]:
np.random.rand(10)*5

array([2.84487285e+00, 2.76097356e+00, 4.26927116e+00, 4.26634622e+00,
       5.28912085e-04, 3.01552652e+00, 3.39227379e-01, 2.95135714e+00,
       1.79470552e+00, 3.72917501e+00])

#### Read the help for np.linspace function and create an array of 11 evenly spaced elements between 0 and 2

In [28]:
np.linspace(0, 2, num=11)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

#### Create a 3 by 4 array of ones

In [29]:
np.ones((3, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

#### Create a 3 by 4 array of fives

In [30]:
np.ones((3, 4), dtype=int)*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

#### Create a 3x3 matrix with values ranging from 0 to 8 (use reshape)

In [31]:
np.arange(9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Element selection
Using the following arrays `a` and `m`

In [2]:
a = np.arange(10,21)
a

NameError: name 'np' is not defined

In [3]:
m = np.arange(1,22).reshape((3,7))
m

NameError: name 'np' is not defined

### Create an array containing... 
#### the first 4 elements of a

In [4]:
a[0:4]

NameError: name 'a' is not defined

#### the last 3 elements of a

In [35]:
a[-3:]

array([18, 19, 20])

#### The middle elements of a from 15 to 18 inclusive

In [36]:
a[5:9]

array([15, 16, 17, 18])

#### The first column of m

In [1]:
m[...,0]
m[:,0]

NameError: name 'm' is not defined

#### The middle row of m

In [38]:
m[1]

array([ 8,  9, 10, 11, 12, 13, 14])

#### The left 3 columns of m

In [39]:
m[:,:3]

array([[ 1,  2,  3],
       [ 8,  9, 10],
       [15, 16, 17]])

#### The bottom-right 2 by 2 square

In [40]:
m[-2:,-2:]

array([[13, 14],
       [20, 21]])

#### (bonus) every other element of a  

In [41]:
a[0::2]

array([10, 12, 14, 16, 18, 20])

#### Subtract 5 from each element of a

In [42]:
a[:]-5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

#### Create an array containing squares of all numbers from 1 to 10 (inclusive)

In [43]:
arr = np.arange(1, 11)
np.power(arr, 2)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

#### Create an array containing all powers of 2 from $2^0$ to $2^{10}$ (inclusive)

In [44]:
#func 1
baseArray = np.ones(11, dtype=int)*2
powersArray = np.arange(0, 11)
np.power(baseArray, powersArray)

#func 2
((np.ones(11) * 2) ** np.arange(0, 11)).astype(np.int)

#func 3
2 ** np.arange(11, dtype=int)

array([   1,    2,    4,    8,   16,   32,   64,  128,  256,  512, 1024])

#### Same as above (powers of two), but subtract one from each element, that is $a_k = 2^k - 1$

In [45]:
baseArray = np.ones(11, dtype=int)*2
powersArray = np.arange(0, 11)
np.power(baseArray, powersArray) -1

array([   0,    1,    3,    7,   15,   31,   63,  127,  255,  511, 1023])

### Bonus task
Write code that lists all available dtypes with specified number of bits 

In [60]:
for k in np.sctypes:
    if k == 'others':
        continue
    for t in np.sctypes[k]:
        val = t().dtype
        print("%s: %s bits" % (val.name, val.itemsize*8))


int8: 8 bits
int16: 16 bits
int32: 32 bits
int64: 64 bits
uint8: 8 bits
uint16: 16 bits
uint32: 32 bits
uint64: 64 bits
float16: 16 bits
float32: 32 bits
float64: 64 bits
float128: 128 bits
complex64: 64 bits
complex128: 128 bits
complex256: 256 bits
