In [51]:
import numpy as np

In [52]:
# arr = np.random.randint(0, high=4, size=(3, 3))
# arr

In [53]:
# col_sums = np.sum(arr, axis=0)
# row_sums = np.sum(arr, axis=1)
# col_ind = np.argmin(col_sums)  
# row_ind = np.argmin(row_sums)
# answer = (row_ind, col_ind)
# answer

In [54]:

    
arr = np.random.randint(0, high=4, size=(3, 3))

col_sums = np.sum(arr, axis=0)
row_sums = np.sum(arr, axis=1)
col_ind = np.argmin(col_sums)  
row_ind = np.argmin(row_sums)
min_index = (row_ind, col_ind)
min_index

(0, 1)

In [55]:
car_data = np.random.randint(0, high=130, size=(10, 2))
car_data

array([[ 15,  35],
       [ 41,  87],
       [ 81, 104],
       [ 25,  74],
       [ 80, 129],
       [102,  95],
       [ 19,  63],
       [ 95,  81],
       [ 40,  23],
       [111,  34]])

In [56]:
speedometer = car_data[:,:1]
tachometer = car_data[:,1:]

In [57]:
N = np.zeros((4, 3), dtype=int)
    
x = np.fill_diagonal(N, 1)
np.flip(N, axis = 0)
np.fill_diagonal(N, 1)



In [50]:
def xmatrix(N): 
    np.fill_diagonal(N, 1)
    np.flip(N, axis=0)
    np.fill_diagonal(N, 1)
    return np.zeros((N, N), dtype=int)

xmatrix(4)

AttributeError: 'int' object has no attribute 'ndim'

In [16]:
# x = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])

N = 7
N = np.zeros((N, N), dtype=int)

np.fill_diagonal(x, 1)
x1 = np.flip(x, axis=0)
np.fill_diagonal(x1, 1)
x1

AttributeError: 'NoneType' object has no attribute 'ndim'

In [17]:
def xmatrix(N):
    a = np.zeros((N, N), int)
    np.fill_diagonal(a, 1)
    b = np.flip(a, axis=0)
    np.fill_diagonal(b, 1)
    return b

xmatrix(7)

array([[1, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 1]])

In [18]:
a = [4, 3, 5, 7, 6, 8]
indices = [0, 1, 4]
np.take(a, indices)

array([4, 3, 6])

In [19]:
cardata = np.random.randint(0, high=130, size=(10, 2))
car_data

array([[ 63, 105],
       [ 36,  92],
       [ 44,  66],
       [ 92,  97],
       [  4,  18],
       [ 94, 102],
       [ 54, 127],
       [ 54,  66],
       [ 33,  77],
       [  7,   6]])

In [49]:
no_shift = np.array(   [[  26.4, 2244. ],
                        [  28.2, 2397. ],
                        [  30. , 2550. ],
                        [  31.8, 2703. ],
                        [  33.6, 2856. ]])
yes_shift = no_shift.copy()
yes_shift[0, 1] = yes_shift[0, 0] * 105

def was_gear_switched(car_data):
    speed = car_data[:,0]
    rpm = car_data[:,1]
    ratios = rpm / speed
    the_diffs = np.abs(np.diff(ratios))
    for n in the_diffs:
        if(n >= 10):
            return True
    return False
    


was_gear_switched(no_shift)


no_shift = np.array(   [[  26.4, 2244. ],
                        [  28.2, 2397. ],
                        [  30. , 2550. ],
                        [  31.8, 2703. ],
                        [  33.6, 2856. ]])
yes_shift = no_shift.copy()
yes_shift[0, 1] = yes_shift[0, 0] * 105

speed = no_shift[:,0]
rpm = no_shift[:,1]
ratios = rpm / speed

speed = yes_shift[:,0]
rpm = yes_shift[:,1]
ratios = rpm / speed

diffs = np.abs(np.diff(ratios))

np.unique(diffs).size

        

2

In [21]:
a = np.array([[1, 2], [3, 4]])
np.std(car_data)

# np.std(a, axis=0)

# np.std(a, axis=1)

35.64445959753072

In [22]:
def was_gear_switched(car_data):
    speed = car_data[:,0]
    rpm = car_data[:,1]
    ratios = rpm / speed
    differences = np.abs(np.differences(ratios))
    for n in differences:
        if(n >= 10):
            return True
    return False

In [23]:
np.random.randint([10, 10])
N = np.zeros((N, N), dtype=int)

TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

In [39]:
no_shift = np.array(   [[  26.4, 2244. ],
                        [  28.2, 2397. ],
                        [  30. , 2550. ],
                        [  31.8, 2703. ],
                        [  33.6, 2856. ]])
yes_shift = no_shift.copy()
yes_shift[0, 1] = yes_shift[0, 0] * 105

speed = car_data[:,0]
rpm = car_data[:,1]
ratios = rpm / speed
differences = np.abs(np.diff(ratios))
    
# np.unique(differences)
differences


array([0.88888889, 1.05555556, 0.44565217, 3.44565217, 3.41489362,
       1.26674547, 1.12962963, 1.11111111, 1.47619048])

In [48]:
n= np.zeros((7,7))
np.diag(n)

array([0., 0., 0., 0., 0., 0., 0.])

In [59]:
def xmatrix(N):
    a = np.zeros((N, N), int)
    np.fill_diagonal(a, 1)
    b = np.flip(a, axis=0)
    np.fill_diagonal(b, 1)
    return b

xmatrix(7)

array([[1, 0, 0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 1, 0, 1, 0, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [1, 0, 0, 0, 0, 0, 1]])